Refactored UA-Clarity-Tools.
UACoreFacilitiesIT/UA-Clarity-Tools pull request #5
Opened 2020-09-11 17:19 UTC by EtienneThompson

ua_clarity_tools.py
        - Made it so get_artifacts is only called when uri_only is not set
            to true.
        - Changed results argument to be default dict() when not specified
            rather than None and redundantly set it to dict() if not
            given another value.
    
test_ua_clarity_tools.py
        - Added check to make sure set container information is the same
            as what should've been scraped to the container_info test.

2020-09-11 19:03 UTC, RyanJohannesBland requested changes

2020-09-11 19:03 UTC, RyanJohannesBland commented on ua_clarity_tools/tests/test_ua_clarity_tools.py
> +import pdb
Please remove.

2020-09-11 19:03 UTC, RyanJohannesBland commented on ua_clarity_tools/tests/test_ua_clarity_tools.py
> +        all_uris.extend(list(in_out_uris.values()))
Are we sure this works? If these values contains lists (I.E. one input mapped to multiple outputs) this appends the list of outputs, not each individual outputs. Your assert using this doesn't fail, but that may be because the step we use to test is 1 to 1.

2020-09-11 19:03 UTC, RyanJohannesBland commented on ua_clarity_tools/tests/test_ua_clarity_tools.py
> +        assert True
Remove please.

2020-09-11 19:03 UTC, RyanJohannesBland commented on ua_clarity_tools/ua_clarity_tools.py
> +import pdb
Remove please.

2020-09-11 19:06 UTC, EtienneThompson commented on ua_clarity_tools/tests/test_ua_clarity_tools.py
> +        assert True
Oh darn :(

2020-09-11 19:06 UTC, EtienneThompson commented on ua_clarity_tools/ua_clarity_tools.py
> +import pdb
Oh darn :(

2020-09-14 18:53 UTC, RyanJohannesBland approved these changes

2020-09-14 18:55 UTC, merged